export default function populateItems(table) {
	return table.set({
		"1": {
			title: "Idioms",
			templateUrl: "https://idioms.thefreedictionary.com/$",
			textSlot: "$",
			spaceReplacement: "-",
			isPopup: false,
		},
		"2": {
			title: "Longman",
			templateUrl: "https://www.ldoceonline.com/dictionary/$",
			textSlot: "$",
			spaceReplacement: "-",
			isPopup: false,
		},
		"3": {
			title: "Merrian",
			templateUrl: "https://www.merriam-webster.com/dictionary/$",
			textSlot: "$",
			spaceReplacement: " ",
			isPopup: false,
		},
		"4": {
			title: "Urban",
			templateUrl: "https://www.urbandictionary.com/define.php?term=$",
			textSlot: "$",
			spaceReplacement: "-",
			isPopup: false,
		},
		"C": {
			title: "Cambridge",
			templateUrl: "https://dictionary.cambridge.org/us/dictionary/english/$",
			textSlot: "$",
			spaceReplacement: "-",
			isPopup: false,
		},
		"X": {
			title: "Cambridge Popup",
			templateUrl: "https://dictionary.cambridge.org/us/dictionary/english/$",
			textSlot: "$",
			spaceReplacement: "-",
			isPopup: true,
		},
		"Z": {
			title: "PT Cambridge",
			templateUrl: "https://dictionary.cambridge.org/us/dictionary/english-portuguese/$",
			textSlot: "$",
			spaceReplacement: "-",
			isPopup: false,
		},
		"S": {
			title: "Collins",
			templateUrl: "https://www.collinsdictionary.com/dictionary/english/$",
			textSlot: "$",
			spaceReplacement: "-",
			isPopup: false,
		},
		"G": {
			title: "Youglish",
			templateUrl: "https://youglish.com/pronounce/$/english/us?",
			textSlot: "$",
			spaceReplacement: " ",
			isPopup: false,
		},
		"F": {
			title: "Free",
			templateUrl: "https://www.thefreedictionary.com/$",
			textSlot: "$",
			spaceReplacement: "+",
			isPopup: false,
		},
		"T": {
			title: "Translate",
			templateUrl: "https://translate.google.com.br/?sl=en&tl=pt&text=$&op=translate",
			textSlot: "$",
			spaceReplacement: " ",
			isPopup: false,
		},
		"D": {
			title: "Linguee",
			templateUrl: "https://www.linguee.com.br/ingles-portugues/traducao/$.html",
			textSlot: "$",
			spaceReplacement: "+",
			isPopup: false,
		},
		"R": {
			title: "Oxford",
			templateUrl: "https://www.oxfordlearnersdictionaries.com/us/definition/english/$",
			textSlot: "$",
			spaceReplacement: "-",
			isPopup: false,
		},
		"H": {
			title: "Thesaurus",
			templateUrl: "https://www.merriam-webster.com/thesaurus/$",
			textSlot: "$",
			spaceReplacement: " ",
			isPopup: false,
		},
	});
}
